import { KnowledgeDeck } from "@/components/knowledge-deck";
import { SiteHeader } from "@/components/site-header";

export default function Home() {
  return (
    <main className="app-shell">
      <SiteHeader />

      <KnowledgeDeck />

      <footer className="app-footer">
        <span>ISSUES → NOTES → REPORTS</span>
        <span>Notes generated by Claude from closed GitHub issues.</span>
      </footer>
    </main>
  );
}
